# Generated by Django 4.2.9 on 2026-10-02 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='调查单号')),
                ('responsible_dept', models.CharField(blank=True, max_length=100, verbose_name='责任部门')),
                ('snapshot_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='盘点基准账面数量')),
                ('counted_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='实盘数量')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True, verbose_name='快照时间')),
                ('status', models.CharField(choices=[('investigating', '调查中'), ('closed', '已结案'), ('revoked', '已撤销'), ('cancelled', '已作废')], default='investigating', max_length=20, verbose_name='状态')),
                ('conclusion', models.TextField(blank=True, verbose_name='调查结论')),
                ('close_baseline_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='结案时账面数量')),
                ('baseline_changed', models.BooleanField(default=False, verbose_name='结案时基准已变化')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='作废原因')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结案时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_investigations', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investigations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_investigations', to='warehouse.goods', verbose_name='货物')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_investigations', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_investigations', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
            ],
            options={
                'verbose_name': '盘点差异调查单',
                'verbose_name_plural': '盘点差异调查单',
                'db_table': 'wh_stocktake_investigation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stocktake', '盘点调整'), ('reversal', '撤销冲回')], max_length=20, verbose_name='分录类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调整数量')),
                ('before_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调整前数量')),
                ('after_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='调整后数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='warehouse.goods', verbose_name='货物')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='warehouse.stocktakeinvestigation', verbose_name='调查单')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='warehouse.stockadjustment', verbose_name='被冲回分录')),
            ],
            options={
                'verbose_name': '库存调整分录',
                'verbose_name_plural': '库存调整分录',
                'db_table': 'wh_stock_adjustment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reason', '原因分析'), ('evidence', '证据材料'), ('review', '复核意见')], max_length=20, verbose_name='记录类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_notes', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='warehouse.stocktakeinvestigation', verbose_name='调查单')),
            ],
            options={
                'verbose_name': '调查过程记录',
                'verbose_name_plural': '调查过程记录',
                'db_table': 'wh_investigation_note',
                'ordering': ['created_at'],
            },
        ),
    ]
