# Generated by Django 4.2.9 on 2026-10-02 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='调查单号')),
                ('snapshot_counted_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='盘点发现值（快照）')),
                ('snapshot_system_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='系统库存值（快照）')),
                ('snapshot_diff', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='初始差额（发现值-系统值，快照）')),
                ('baseline_ledger_id', models.BigIntegerField(blank=True, help_text='立案时该货物最新流水；结案据此检测基线是否被后续收发推进', null=True, verbose_name='基线流水ID')),
                ('responsibility_scope', models.CharField(max_length=200, verbose_name='责任范围')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='责任人')),
                ('location_scope', models.CharField(blank=True, max_length=100, verbose_name='盘点责任区域')),
                ('status', models.CharField(choices=[('investigating', '调查中'), ('approved', '已批准'), ('rejected', '已驳回'), ('reversed', '已撤销')], default='investigating', max_length=20, verbose_name='状态')),
                ('closed_system_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='结案时系统值')),
                ('recalculated_diff', models.DecimalField(blank=True, decimal_places=2, help_text='发现值快照 - 结案时系统值（含调查期间收发）', max_digits=12, null=True, verbose_name='结案重算差额')),
                ('baseline_changed', models.BooleanField(blank=True, help_text='调查期间是否发生过影响库存的收发', null=True, verbose_name='基线是否已变化')),
                ('approval_opinion', models.TextField(blank=True, verbose_name='批准/驳回意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='结案时间')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '盘点差异调查单',
                'verbose_name_plural': '盘点差异调查单',
                'db_table': 'wh_investigation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('stock_in', '入库'), ('stock_out', '出库'), ('adjustment', '盘点调整'), ('adjustment_reversal', '调整冲回')], max_length=20, verbose_name='分录类型')),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='带符号：入库/盘盈为正，出库/盘亏为负', max_digits=12, verbose_name='数量变动')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动后结余')),
                ('ref_type', models.CharField(blank=True, max_length=30, verbose_name='来源单据类型')),
                ('ref_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('remark', models.TextField(blank=True, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记账时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存流水分录',
                'verbose_name_plural': '库存流水分录',
                'db_table': 'wh_stock_ledger_entry',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reason', '差异原因'), ('evidence', '证据'), ('review', '复核意见')], max_length=20, verbose_name='记录类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('attachment_ref', models.CharField(blank=True, max_length=200, verbose_name='证据附件引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='warehouse.investigation', verbose_name='调查单')),
            ],
            options={
                'verbose_name': '调查记录',
                'verbose_name_plural': '调查记录',
                'db_table': 'wh_investigation_record',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='adjustment_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigation_adjustments', to='warehouse.stockledgerentry', verbose_name='调整分录'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_investigations', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investigations', to=settings.AUTH_USER_MODEL, verbose_name='立案人'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='warehouse.goods', verbose_name='货物'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='reversal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigation_reversals', to='warehouse.stockledgerentry', verbose_name='冲回分录'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_investigations', to=settings.AUTH_USER_MODEL, verbose_name='撤销人'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['goods', 'id'], name='wh_stock_le_goods_i_d5c856_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['ref_type', 'ref_id'], name='wh_stock_le_ref_typ_b1b46c_idx'),
        ),
    ]
